import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import InnerLayout from "@/layouts/innerLayout";
import ContextProvider from "@/provider/contextProvider";

const inter = Roboto({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <InnerLayout>
            {children}
          </InnerLayout>
        </ContextProvider>
      </body>
    </html>
  );
}
